"""Add Sandi Pramuka models

Revision ID: 2007d6db617f
Revises: 89f3741b3905
Create Date: 2026-02-02 01:13:43.161071+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2007d6db617f'
down_revision: Union[str, Sequence[str], None] = '89f3741b3905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandi_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codename', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('encoding', 'substitution', 'transposition', 'visual', name='sandi_category'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandi_types_category'), 'sandi_types', ['category'], unique=False)
    op.create_index(op.f('ix_sandi_types_codename'), 'sandi_types', ['codename'], unique=True)
    op.create_table('encryption_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sandi_id', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('operation_mode', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sandi_id'], ['sandi_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encryption_logs_input_hash'), 'encryption_logs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_encryption_logs_sandi_id'), 'encryption_logs', ['sandi_id'], unique=False)
    op.create_index(op.f('ix_encryption_logs_timestamp'), 'encryption_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_encryption_logs_user_id'), 'encryption_logs', ['user_id'], unique=False)
    op.create_table('sandi_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sandi_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('encrypted_text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sandi_id'], ['sandi_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandi_questions_sandi_id'), 'sandi_questions', ['sandi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandi_questions_sandi_id'), table_name='sandi_questions')
    op.drop_table('sandi_questions')
    op.drop_index(op.f('ix_encryption_logs_user_id'), table_name='encryption_logs')
    op.drop_index(op.f('ix_encryption_logs_timestamp'), table_name='encryption_logs')
    op.drop_index(op.f('ix_encryption_logs_sandi_id'), table_name='encryption_logs')
    op.drop_index(op.f('ix_encryption_logs_input_hash'), table_name='encryption_logs')
    op.drop_table('encryption_logs')
    op.drop_index(op.f('ix_sandi_types_codename'), table_name='sandi_types')
    op.drop_index(op.f('ix_sandi_types_category'), table_name='sandi_types')
    op.drop_table('sandi_types')
    # ### end Alembic commands ###
