"""add cyber challenges

Revision ID: 42edeaf3781e
Revises: c6ca8d09859d
Create Date: 2026-01-21 07:12:00.705250+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42edeaf3781e'
down_revision: Union[str, Sequence[str], None] = 'c6ca8d09859d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_challenges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('morse', 'semaphore', 'caesar_cipher', 'rail_fence', name='cyber_category'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('encrypted_data', sa.JSON(), nullable=False),
    sa.Column('decrypted_answer', sa.String(length=200), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cyber_challenges_category'), 'cyber_challenges', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cyber_challenges_category'), table_name='cyber_challenges')
    op.drop_table('cyber_challenges')
    # ### end Alembic commands ###
