"""Add streak and last_active_date to users

Revision ID: 533267a7f5d4
Revises: f18817b0db72
Create Date: 2026-01-25 02:30:45.326867+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533267a7f5d4'
down_revision: Union[str, Sequence[str], None] = 'f18817b0db72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add streak column with default value 0 for existing rows
    op.add_column('users', sa.Column('streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'streak')
    # ### end Alembic commands ###
