"""sku twin pillars

Revision ID: 5e864ed44314
Revises: b275e914e1fb
Create Date: 2026-01-22 06:07:09.929468+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e864ed44314'
down_revision: Union[str, Sequence[str], None] = 'b275e914e1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_points',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('bantara', 'laksana', name='skulevel'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quiz_content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku_point_id', sa.String(length=50), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sku_point_id'], ['sku_points.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'sku_point_id')
    )
    op.drop_index(op.f('ix_khasyaraka_sku_tasks_id'), table_name='khasyaraka_sku_tasks')
    op.drop_table('khasyaraka_sku_tasks')
    op.drop_index(op.f('ix_khasyaraka_sku_points_id'), table_name='khasyaraka_sku_points')
    op.drop_table('khasyaraka_sku_points')
    op.drop_index(op.f('ix_khasyaraka_sku_levels_id'), table_name='khasyaraka_sku_levels')
    op.drop_table('khasyaraka_sku_levels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khasyaraka_sku_points',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['khasyaraka_sku_levels.id'], name=op.f('khasyaraka_sku_points_level_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('khasyaraka_sku_points_pkey'))
    )
    op.create_index(op.f('ix_khasyaraka_sku_points_id'), 'khasyaraka_sku_points', ['id'], unique=False)
    op.create_table('khasyaraka_sku_levels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('level_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color_hex', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('khasyaraka_sku_levels_pkey'))
    )
    op.create_index(op.f('ix_khasyaraka_sku_levels_id'), 'khasyaraka_sku_levels', ['id'], unique=False)
    op.create_table('khasyaraka_sku_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['khasyaraka_sku_points.id'], name=op.f('khasyaraka_sku_tasks_point_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('khasyaraka_sku_tasks_pkey'))
    )
    op.create_index(op.f('ix_khasyaraka_sku_tasks_id'), 'khasyaraka_sku_tasks', ['id'], unique=False)
    op.drop_table('sku_progress')
    op.drop_table('sku_points')
    # ### end Alembic commands ###
