"""add cyber modules

Revision ID: 6e525eed181d
Revises: 26c28ff032df
Create Date: 2026-01-21 08:19:56.730745+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e525eed181d'
down_revision: Union[str, Sequence[str], None] = '26c28ff032df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_modules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('original_title', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('min_read_seconds', sa.Integer(), nullable=False),
    sa.Column('intel_content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cyber_challenges', sa.Column('module_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_cyber_challenges_module_id'), 'cyber_challenges', ['module_id'], unique=False)
    op.create_foreign_key(None, 'cyber_challenges', 'cyber_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cyber_challenges', type_='foreignkey')
    op.drop_index(op.f('ix_cyber_challenges_module_id'), table_name='cyber_challenges')
    op.drop_column('cyber_challenges', 'module_id')
    op.drop_table('cyber_modules')
    # ### end Alembic commands ###
