"""add_training_and_sku_models

Revision ID: 96c80d0531b5
Revises: ffbfdd990855
Create Date: 2026-01-20 05:45:56.042596+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c80d0531b5'
down_revision: Union[str, Sequence[str], None] = 'ffbfdd990855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khasyaraka_sku_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khasyaraka_sku_levels_id'), 'khasyaraka_sku_levels', ['id'], unique=False)
    op.create_table('khasyaraka_special_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_title', sa.String(length=200), nullable=False),
    sa.Column('level_category', sa.String(length=50), nullable=False),
    sa.Column('badge_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khasyaraka_special_missions_id'), 'khasyaraka_special_missions', ['id'], unique=False)
    op.create_table('khasyaraka_training_paths',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sections',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('khasyaraka_mission_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('correct_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['khasyaraka_special_missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khasyaraka_mission_tasks_id'), 'khasyaraka_mission_tasks', ['id'], unique=False)
    op.create_table('khasyaraka_sku_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['khasyaraka_sku_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khasyaraka_sku_points_id'), 'khasyaraka_sku_points', ['id'], unique=False)
    op.create_table('training_units',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('total_levels', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['training_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('khasyaraka_sku_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('correct_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['khasyaraka_sku_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_khasyaraka_sku_tasks_id'), 'khasyaraka_sku_tasks', ['id'], unique=False)
    op.create_table('training_levels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('unit_id', sa.String(length=50), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('min_correct', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('unlock_rule', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['training_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_questions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('level_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['training_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_questions')
    op.drop_table('training_levels')
    op.drop_index(op.f('ix_khasyaraka_sku_tasks_id'), table_name='khasyaraka_sku_tasks')
    op.drop_table('khasyaraka_sku_tasks')
    op.drop_table('training_units')
    op.drop_index(op.f('ix_khasyaraka_sku_points_id'), table_name='khasyaraka_sku_points')
    op.drop_table('khasyaraka_sku_points')
    op.drop_index(op.f('ix_khasyaraka_mission_tasks_id'), table_name='khasyaraka_mission_tasks')
    op.drop_table('khasyaraka_mission_tasks')
    op.drop_table('training_sections')
    op.drop_table('khasyaraka_training_paths')
    op.drop_index(op.f('ix_khasyaraka_special_missions_id'), table_name='khasyaraka_special_missions')
    op.drop_table('khasyaraka_special_missions')
    op.drop_index(op.f('ix_khasyaraka_sku_levels_id'), table_name='khasyaraka_sku_levels')
    op.drop_table('khasyaraka_sku_levels')
    # ### end Alembic commands ###
