"""cyber level progress

Revision ID: b275e914e1fb
Revises: 6e525eed181d
Create Date: 2026-01-21 23:58:54.488974+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b275e914e1fb'
down_revision: Union[str, Sequence[str], None] = '6e525eed181d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_level_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['cyber_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', 'level', name='uq_user_module_level')
    )
    op.create_index(op.f('ix_cyber_level_progress_module_id'), 'cyber_level_progress', ['module_id'], unique=False)
    op.create_index(op.f('ix_cyber_level_progress_user_id'), 'cyber_level_progress', ['user_id'], unique=False)
    op.add_column('cyber_challenges', sa.Column('level', sa.Integer(), nullable=True, server_default='1'))
    op.execute("UPDATE cyber_challenges SET level = 1 WHERE level IS NULL")
    op.execute("""
        UPDATE cyber_challenges
        SET module_id = CASE
            WHEN category = 'morse' THEN 'mod_morse'
            WHEN category = 'semaphore' THEN 'mod_semaphore'
            WHEN category = 'rail_fence' THEN 'mod_kotak1'
            WHEN category = 'caesar_cipher' THEN 'mod_an'
            ELSE module_id
        END
        WHERE module_id IS NULL
    """)
    op.alter_column('cyber_challenges', 'level', nullable=False, server_default=None)
    op.alter_column('cyber_challenges', 'module_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cyber_challenges', 'module_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('cyber_challenges', 'level')
    op.drop_index(op.f('ix_cyber_level_progress_user_id'), table_name='cyber_level_progress')
    op.drop_index(op.f('ix_cyber_level_progress_module_id'), table_name='cyber_level_progress')
    op.drop_table('cyber_level_progress')
    # ### end Alembic commands ###
