"""add cyber progress

Revision ID: eca635ea1834
Revises: 42edeaf3781e
Create Date: 2026-01-21 07:42:31.801645+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca635ea1834'
down_revision: Union[str, Sequence[str], None] = '42edeaf3781e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_solved_challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=50), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['cyber_challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge')
    )
    op.create_index(op.f('ix_user_solved_challenges_challenge_id'), 'user_solved_challenges', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_solved_challenges_user_id'), 'user_solved_challenges', ['user_id'], unique=False)
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hack_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('decrypted_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'decrypted_count')
    op.drop_column('users', 'hack_level')
    op.drop_column('users', 'total_xp')
    op.drop_index(op.f('ix_user_solved_challenges_user_id'), table_name='user_solved_challenges')
    op.drop_index(op.f('ix_user_solved_challenges_challenge_id'), table_name='user_solved_challenges')
    op.drop_table('user_solved_challenges')
    # ### end Alembic commands ###
