"""Add TKK and UserTKK models

Revision ID: ef8916f3f2d3
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 12:09:52.963419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8916f3f2d3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tkk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tkk_slug', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('PURWA', 'MADYA', 'UTAMA', name='tkklevel'), nullable=False),
    sa.Column('attained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tkk_slug', 'level', name='uq_user_tkk_level')
    )
    op.create_index(op.f('ix_user_tkk_id'), 'user_tkk', ['id'], unique=False)
    op.create_index(op.f('ix_user_tkk_tkk_slug'), 'user_tkk', ['tkk_slug'], unique=False)
    op.create_index(op.f('ix_user_tkk_user_id'), 'user_tkk', ['user_id'], unique=False)
    op.drop_index(op.f('idx_sub_payment_ref_unique'), table_name='subscriptions', postgresql_where='(payment_reference IS NOT NULL)')
    op.drop_index(op.f('idx_sub_user_active'), table_name='subscriptions', postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_index(op.f('idx_sub_user_active'), 'subscriptions', ['user_id', 'status', sa.literal_column('end_date DESC')], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('idx_sub_payment_ref_unique'), 'subscriptions', ['payment_reference'], unique=True, postgresql_where='(payment_reference IS NOT NULL)')
    op.drop_index(op.f('ix_user_tkk_user_id'), table_name='user_tkk')
    op.drop_index(op.f('ix_user_tkk_tkk_slug'), table_name='user_tkk')
    op.drop_index(op.f('ix_user_tkk_id'), table_name='user_tkk')
    op.drop_table('user_tkk')
    # ### end Alembic commands ###
