"""add_survival_gps_tracker_stats

Revision ID: f18817b0db72
Revises: 8f4e4b7bef1e
Create Date: 2026-01-23 00:54:05.479238+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18817b0db72'
down_revision: Union[str, Sequence[str], None] = '8f4e4b7bef1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tooltype ADD VALUE IF NOT EXISTS 'gps_tracker'")
    op.add_column(
        'survival_mastery',
        sa.Column('max_altitude', sa.Float(), nullable=False, server_default='0')
    )
    op.add_column(
        'survival_mastery',
        sa.Column('total_distance_tracked', sa.Float(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survival_mastery', 'total_distance_tracked')
    op.drop_column('survival_mastery', 'max_altitude')
    # ### end Alembic commands ###
