"""Add picture_url

Revision ID: ffbfdd990855
Revises: f6a63e1b9da8
Create Date: 2026-01-17 08:17:11.016999+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbfdd990855'
down_revision: Union[str, Sequence[str], None] = 'f6a63e1b9da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture_url')
    # ### end Alembic commands ###
